baseURL = "https://nrise.github.io/"
languageCode = "ko-KR"
title = "NRISE ENGINEERING BLOG"
theme = "hugo_theme_pickles"
copyright = "Copyright 2011-{year} NRISE, Inc. All rights reserved."

[params]
 ga_api_key = "UA-56246190-2"
